### ISSUE TITLE
[Proposal] Add easily clickable "copy" button

### ISSUE THREAD

**Issue by rcmorano** [andalugeeks/andaluh-www#8]
It would be cool to have a copy button. It would ease the copypaste process for transcripted messages. 

It would accelerate expansion process of the Andalûh.

**Use case:** You **write** a message in Castellano, hit the **TAB** key to change the focus to the copy button and finally hit the **Space** key actually **copy** the transcripted message.

**Comment by fontanon** [comment]
Good point @rcmorano .. actually I'd like to add that some "social share" buttons could help. Something like:

![Share buttons](https://drive.google.com/uc?export=view&id=1mfmi37Cb5bHsyFz8trzCJ80F2ktJk8fB)

**Comment by fontanon** [comment]
PR #12 resolves this.

**Comment by fontanon** [comment]
Hi. I'd actually like to reopen this in order to submit a [FEAT REQUEST]:

- Posting the "andalusian" text along with the short url generated link. That way, people could use the "share" buttons to both sharing their message, which is the goal of andaluh-www. The shourt url link is only to provide traceability from spanish.

- Generate a fancy generic bookmarklet so when sharing shorturl a preview is displayed.

Do you think @emrivero this is something achievable?

**Comment by fontanon** [comment]
I've took some notes and screenshots in order to specify the FEAT REQ better:

* Andaluh-www: Replace `Copiâh link` and `Compartîh link` with simpli `Copiâh` an `Compartîh`, because both text and link will be copied. Append `shortlink` by end of andalusian `text` when copying and sharing. https://drive.google.com/file/d/17CwKjVoO-SHZ2Kksn-VNrIsEy6GWeRik/view?usp=sharing

* Social share: Post both message and link. Bookmarklet needs to be generated. https://drive.google.com/file/d/1OzYVukBT8Y-cVsf02ITIEh336EvL_8V9/view?usp=sharing

Please notice TWITTER has a 280 char max length for messages (tweets). Considering andaluh shortlinks has a fixed length, I guess the social share could cut the length of the tweet in order to inject the url at the end. Example:

This original text in spanish:

```
Esto es un post para twitter que es tan largo que va a ser recortado cuando se intente compartir en dicha red 
social, por tanto lo suyo es recortar el final con algo así como [...] y entonces meter la url corta a la finalización 
para que todo entre en los 280 caracteres que de máximo te permite twitter.
``` 

Would end up on twitter shared as:

```
Êtto êh un pôtt pa twîttêh que êh tan largo que ba a çêh recortao cuando çe intente compartîh en dixa ré çoçiâh, 
por tanto lo çuyo êh recortâh er finâh con argo açí como [...] y entonçê metêh la ûl-r corta a la finaliçaçión pa 
que tó entre en lô 28[...] https://s.andaluh.es/2o4k8
```

**Comment by fontanon** [comment]
Copy Button already available.
